-- =================================================================
-- EX 603 Assignment 2 — schema.sql
-- Theme: <>
-- Author: <Samrawit Alemu>
-- Target: PostgreSQL 14+
-- =================================================================
-- Reset. Reverse creation order, so no dependency blocks a drop.

DROP TABLE IF EXISTS user_fav_prp;
DROP TABLE IF EXISTS booking;
DROP TABLE IF EXISTS property;
DROP TABLE IF EXISTS host;
DROP TABLE IF EXISTS "user";

CREATE TABLE "user" (
                        user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        firstname VARCHAR(100) NOT NULL,
                        lastname VARCHAR(100) NOT NULL,
                        email VARCHAR(255) NOT NULL UNIQUE,
                        phone VARCHAR(30)
);

CREATE TABLE host (
                      host_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      user_id BIGINT NOT NULL UNIQUE,
                      host_since DATE,
                      rating NUMERIC(3,2),
                      CONSTRAINT fk_host_user
                          FOREIGN KEY (user_id) REFERENCES "user"(user_id),
                      CONSTRAINT chk_host_rating
                          CHECK (rating IS NULL OR rating BETWEEN 0 AND 5)
);

CREATE TABLE property (
                          property_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          host_id BIGINT NOT NULL,
                          title VARCHAR(255) NOT NULL,
                          address TEXT NOT NULL,
                          property_type VARCHAR(100),
                          price_per_night NUMERIC(10,2) NOT NULL,
                          CONSTRAINT fk_property_host
                              FOREIGN KEY (host_id) REFERENCES host(host_id),
                          CONSTRAINT chk_property_price
                              CHECK (price_per_night >= 0)
);

CREATE TABLE booking (
                         booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         user_id BIGINT NOT NULL,
                         property_id BIGINT NOT NULL,
                         check_in_date DATE NOT NULL,
                         check_out_date DATE NOT NULL,
                         total_price NUMERIC(10,2) NOT NULL,
                         CONSTRAINT fk_booking_user
                             FOREIGN KEY (user_id) REFERENCES "user"(user_id),
                         CONSTRAINT fk_booking_property
                             FOREIGN KEY (property_id) REFERENCES property(property_id),
                         CONSTRAINT chk_booking_dates
                             CHECK (check_out_date > check_in_date),
                         CONSTRAINT chk_booking_total_price
                             CHECK (total_price >= 0)
);

CREATE TABLE user_fav_prp (
                              user_id BIGINT NOT NULL,
                              property_id BIGINT NOT NULL,
                              date_added TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                              CONSTRAINT pk_user_fav_prp PRIMARY KEY (user_id, property_id),
                              CONSTRAINT fk_user_fav_prp_user
                                  FOREIGN KEY (user_id) REFERENCES "user"(user_id),
                              CONSTRAINT fk_user_fav_prp_property
                                  FOREIGN KEY (property_id) REFERENCES property(property_id)
);